title: "StockPal"
remote_theme: jekyll/minima@v2.5.1

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2324S2-CS2113T-T09-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
  - jekyll-remote-theme